# Generated by Django 6.0.5 on 2026-05-11 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_values', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_uid', models.CharField(max_length=64)),
                ('count_requested', models.PositiveSmallIntegerField()),
                ('count_succeeded', models.PositiveSmallIntegerField(default=0)),
                ('count_failed', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('schema_snapshot', models.JSONField(blank=True, default=dict)),
                ('field_faker_map', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='draft_attachments/')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dummygenerator.submissiondraft')),
            ],
        ),
        migrations.AddField(
            model_name='submissiondraft',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='dummygenerator.submissionjob'),
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dummygenerator.submissionjob')),
            ],
        ),
    ]
